# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '上传' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 上传

  target '上传Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '上传UITests' do
    inherit! :search_paths
    # Pods for testing
  end
   pod 'Qiniu', '~> 7.2.3'
end
